default:
  image: alpine:latest

stages:
  - prebuild
  - build

variables:
  DEPENDENCY_JOB_NAME: "prebuildit"
  ARTIFACTS_DOWNLOAD_REF: $CI_COMMIT_BRANCH

prebuildit:
  stage: prebuild
  script:
    - |
        set -euvx
        export UPSTREAM_PROJECT="${UPSTREAM_PROJECT:-gitlab-gold/ryan-test-subgroup/label-test}"
        export UPSTREAM_REF="${UPSTREAM_REF:-${CI_COMMIT_BRANCH}}"
        export UPSTREAM_JOB="${UPSTREAM_JOB:-buildit}"
        tee prebuildit.env <<EOF
        UPSTREAM_PROJECT=$UPSTREAM_PROJECT
        UPSTREAM_REF=$UPSTREAM_REF
        UPSTREAM_JOB=$UPSTREAM_JOB
        EOF
    - export
  artifacts:
    reports:
      dotenv: prebuildit.env
    paths:
      - prebuildit.env

buildit:
  stage: build
  needs:
    - job: prebuildit
      artifacts: true
  script:
    - echo $DEPENDENCY_JOB_NAME
    - echo $ARTIFACTS_DOWNLOAD_REF
    - echo $UPSTREAM_PROJECT
    - echo $UPSTREAM_REF
    - echo $UPSTREAM_JOB
    - export | tee "${CI_PROJECT_PATH_SLUG}_${CI_JOB_STAGE}_${CI_JOB_NAME}.export"
    - ls -lah
  artifacts:
    when: always
    paths:
      - ./*.export
      - prebuildit.env
  trigger:
    include:
      - local: gitlab-gold/ryan-test-subgroup/label-test/test-dir/.gitlab-ci.yml
    strategy: depend

  # needs:
  #   - job: prebuildit
  #   - project: $UPSTREAM_PROJECT
  #     ref: $UPSTREAM_REF
  #     job: $UPSTREAM_JOB
  #     artifacts: true
  # script:
  #   - export | tee "${CI_PROJECT_PATH_SLUG}_${CI_JOB_STAGE}_${CI_JOB_NAME}.export"
  #   - ls -lah
  # artifacts:
  #   when: always
  #   paths:
  #     - ./*.export

